"""
project_01_research_assistant/agents.py
-----------------------------------------
Agent definitions for the 5-agent research pipeline.

Roles:
1. Orchestrator — breaks topic into sub-questions, coordinates
2. Researcher — gathers and synthesizes information
3. FactChecker — verifies claims and flags uncertainties
4. Analyst — identifies patterns and generates insights
5. ReportWriter — produces the final structured report
"""

from autogen import AssistantAgent, UserProxyAgent


def create_research_agents(llm_config: dict) -> dict:
    """Creates all 5 research pipeline agents."""

    orchestrator = AssistantAgent(
        name="Orchestrator",
        system_message="""You are the Research Orchestrator. Your job:
        1. Break the research topic into 3-4 specific sub-questions
        2. For each sub-question, assign it: TASK_FOR_RESEARCHER: [question]
        3. After research is done, signal: TASK_FOR_ANALYST: analyze the findings
        4. After analysis: TASK_FOR_WRITER: create final report
        Be explicit with your task assignments.
        Say ORCHESTRATION_COMPLETE when the writer finishes.""",
        llm_config=llm_config,
        max_consecutive_auto_reply=5,
    )

    researcher = AssistantAgent(
        name="Researcher",
        system_message="""You are a Research Specialist.
        For each assigned sub-question, provide:
        - 3-5 factual points with supporting context
        - Note knowledge limitations honestly
        - Distinguish established facts from emerging/contested claims
        Structure with clear headers.
        End each research section with: RESEARCH_SECTION_DONE""",
        llm_config=llm_config,
        max_consecutive_auto_reply=6,
    )

    fact_checker = AssistantAgent(
        name="FactChecker",
        system_message="""You are a Fact Checker.
        Review research claims and assess:
        - VERIFIED: [claim] — well-established, reliable
        - PLAUSIBLE: [claim] — reasonable but verify independently
        - FLAGGED: [claim] — questionable, outdated, or unverifiable
        Be thorough but constructive.
        End with: FACT_CHECK_DONE""",
        llm_config=llm_config,
        max_consecutive_auto_reply=3,
    )

    analyst = AssistantAgent(
        name="Analyst",
        system_message="""You are a Research Analyst.
        Synthesize all research to identify:
        1. Key patterns and trends (3-5 insights)
        2. Connections between different findings
        3. Significance ratings: HIGH/MEDIUM/LOW impact
        4. Research gaps or areas needing further study
        End with: ANALYSIS_DONE""",
        llm_config=llm_config,
        max_consecutive_auto_reply=3,
    )

    writer = AssistantAgent(
        name="ReportWriter",
        system_message="""You create professional research reports in Markdown.
        Structure:
        # [TOPIC] Research Report

        ## Executive Summary
        [3-5 bullet points of key findings]

        ## Detailed Findings
        [Organized by sub-topic with h3 headers]

        ## Key Insights
        [Numbered insights from analysis]

        ## Fact-Check Notes
        [Any flagged claims or caveats]

        ## Conclusion
        [Synthesis and recommended next steps]

        ---
        *Generated by AutoGen Research Pipeline*

        End with: REPORT_COMPLETE""",
        llm_config=llm_config,
        max_consecutive_auto_reply=2,
    )

    admin = UserProxyAgent(
        name="ResearchAdmin",
        human_input_mode="NEVER",
        code_execution_config=False,
        is_termination_msg=lambda msg: "REPORT_COMPLETE" in msg.get("content", ""),
        max_consecutive_auto_reply=1,
    )

    return {
        "orchestrator": orchestrator,
        "researcher": researcher,
        "fact_checker": fact_checker,
        "analyst": analyst,
        "writer": writer,
        "admin": admin,
    }
